### ISSUE TITLE
Include only implementation reports submitted by maintainers or with their consent

### ISSUE THREAD

**Issue by csarven** [solid-contrib/test-suite#132]
https://github.com/solid/test-suite/blob/main/README.md#table appears to include a (high-level) report about implementations.

Can the table (and information elsewhere) only list implementations that the maintainers of the project's submitted a report for or with their consent (ideally in public record)?

FWIW, this was the approach taken in LDN tests in that the reports were either submitted by the maintainer of the project or with the consent of the maintainer. It allows the submissions to be made and shared in good faith.

See also https://github.com/solid/specification/issues/383

**Comment by michielbdejong** [comment]
That was proposed in the past, but in practice that doesn't work. The main reason is that some implementers go through the effort of properly testing their server, but some don't. So that approach would lead to incomplete and incorrect data.

The only situation where we will not test a server implementation is if that server self-reports as "not (yet) Solid compliant". We don't test teapots. :)

The test suite is not primarily a service to pod hosters and to Solid app developers. Our role as a service to pod server implementers is only secondary. We owe it to our readers to give a complete and honest report of the objective data, not just echo what each implementer self-advertise in their own documentation. There have been repeated cases where implementations self-advertised as "use this as a Solid server" but in reality, it turned out not to be spec compliant. So a self-reporting system like you propose would not work.

Thanks for the suggestion nonetheless!

**Comment by csarven** [comment]
>some implementers go through the effort of properly testing their server, but some don't

What/Who? Why do they end up testing improperly?

>The only situation where we will not test a server implementation is if that server self-reports as "not (yet) Solid compliant"

Is this a well-known and agreed practice? Where do they report not to be compliant? Why is it opt-out instead of opt-in?

---

Claims about an implementation's conformance can surely be done by multiple parties, and what's authoritative and trustable is another matter.

When I suggest that maintainers of a project reporting their test results, it is not merely a claim of "our server is spec compliant". It is very much about tests running in a (semi-)automated or manual mode - whatever is appropriate for a particular test - and generating a structured report that is reproducible in context of the inputs provided.

>but in reality, it turned out not to be spec compliant

Specs need to authoritatively reference tests and reports (hence, issue 383). It is only then we can say that the results/reports generated by a test suite are valid. For specs that have a status other than "final" (1.0 or REC or whatever), the results are questionable. Unless of course the maintainer states that a particular version of an implementation conforms to a particular version of a spec when tested with a particular version of test software. If that (and possibly other) information is not taken into account for testing or communicated in the reports, I would always question the data/claims/reports - it is a major pothole for all sorts of issues: data quality, concept drifts, comparability, communication...

Having said that, there is room for both maintainer submitted reports as well as third-party reporting and/or verification (of maintainers reports). In order to get to reliable third-party reporting, I'd argue that the bar for the quality of tests and reporting is very high especially if the communication is intended to have high degree of authority on the matter. That itself requires multiple layers of checks from people writing test software, writing tests, authors/editors verifying the accuracy and necessary precision of the tests, and a significant sample of reports that can as well be verified. This is important because the community and the world at large will interpret what's authoritative for different reasons.

At the end of the day, specs need to help implementers and within good reason there shouldn't be doubt about the validity of the tests or the results. Hence, my concern about who makes the claim - after all, as you know, anyone can say anything about anything.

**Comment by michielbdejong** [comment]
Yeah, that's why it has to be a collaboration between testers and implementers, so that we put all our knowledge and tools together, adding up to the best information we can compile as a community. And I think in most cases that's going pretty well.

We always ping the implementer in question, of course, and in case of doubt or disagreement, we mark the test as 'disputed' . That ensure that the information we publish is the at least as good as the information that each implementer would publish by themselves.

But if you feel there is room for improvement then maybe we want to call a panel meeting about this topic?

**Comment by RubenVerborgh** [comment]
The technical grounds are that test-suite at the moment is a non-representative list without consensus; and, if anything, there is evidence of serious issues (as documented).

As such, test scores are not fundamentally meaningful as they currently say more about test-suite than about implementations. A quick comparison is using an indoor thermometer to predict the weather: yes, it will give an indication, but it is not sufficient to draw meaningful conclusions. So the table is not helping to the extent it portrays itself to be.

Are you willing to set up a democratic process to decide whether the table should be out, or will it remain a one-person decision?

**Comment by michielbdejong** [comment]
This is something we will decide in the test suite panel.

**Comment by michielbdejong** [comment]
@RubenVerborgh to answer your broad, destructive, and IMNSHO false and unprofessional statement about serious technical issues and non-representativeness in our work, I hereby challenge you to find 1 incorrect test in any part of the test suite and contribute a bug report about that. If you can't find any bugs then I would strongly suggest you stop making value judgements about the work of the test suite panel.

**Comment by RubenVerborgh** [comment]
@michielbdejong The burden of proof that the table in question would be a reliable and representative predictor for client–server interoperability is entirely yours. That is literally your most important job as a test author. You can't hold others to a higher standards than yourself. As spec co-author and implementer, I can only say no such evidence is apparent, and hence there is no evidence for the table evaluating anything but itself.

Also I have no knowledge of the test suite panel endorsing or supporting the relevance of test-suite, so perhaps it is more fair if you didn't speak on their behalf.

**Comment by michielbdejong** [comment]
@RubenVerborgh Focus on technical details please. You just did exactly what I asked you not to do, which makes me think you're either not listening or not willing to change your behaviour. I asked you to focus on technical details and not to make broad statements that you can not back up with any facts. And you did it twice in a row. This incident will be reported to the Code of Conduct committee.

**Comment by michielbdejong** [comment]
Focusing on technical details is not just important because of our community's code of conduct, but also because of the issue we're discussing here:

What should be the process of publishing test reports? I think there are three main cases:

* If implementers self-report results from CI and/or from manual testing, I think we can usually publish those in good faith, unless there is evidence of tampering.

* If the test suite panel reports test results and the implementer has specific technical comments, then we discuss these, and the results are not published until the discussion leads to a conclusion.

* If the test suite panel reports test results and the implementer makes broad negative statements about the panel's work, without going into any technical detail, what should happen? I think that's the trickiest one of the three.

**Comment by RubenVerborgh** [comment]
> You just did exactly what I asked you not to do

Fortunately, I have the right to choose and take responsibility for my own actions.

I did not take the bait to regurgitate widely documented test-suite bugs, because they are not the scope of this issue. You have the duty to stay on topic as much as I do.

> If the test suite panel

You—as an individual, not a group—claim that test-suite is representative. Prove it by showing what percentage of the spec is covered. After all, extraordinary claims require extraordinary evidence.

**What evidence proves the table to be a representative measure of spec compliance that hence should be published?**

Let me list counter-evidence:
- The majority of implementations that pass the table are not compatible with existing apps.
- Multiple implementations that do not pass the table are fully compatible with existing apps.
- In particular, CSS has implemented hundreds of commits implementing crucial to app and spec compatibility behavior. Virtually none of these affect test score.

None of these could be true if the test-suite table were correct and meaningful. Which is why we'd rather not have it as-is.

**Comment by michielbdejong** [comment]
Thanks for going into some more detail. IMHO the level of detail is often what makes the difference between a destructive comment and a constructive one, thank you!

> The majority of implementations that pass the table are not compatible with existing apps.

-> created https://github.com/solid/test-suite/issues/133 about this.

> Multiple implementations that do not pass the table are fully compatible with existing apps.

-> I personally would say that's not a reason to lower the bar, but if you feel we should change our reporting based on that then we'll listen, take that on as a suggestion, and discuss it with the panel. I created https://github.com/solid/test-suite/issues/134 about this.

> In particular, CSS has implemented hundreds of commits implementing crucial app and spec compatibility behavior. Virtually none of these affect test score.

-> that's interesting, we might be able to dig through those to find pointers for new tests we can add. I created https://github.com/solid/test-suite/issues/135 about this.

**Comment by michielbdejong** [comment]
@csarven [Doodle for the meeting about this issue](https://doodle.com/meeting/participate/id/av2R180a) is almost complete, you are the last person missing. Can you please fill in your availability? Thanks!

**Comment by RubenVerborgh** [comment]
> lower the bar

No one's asking; we want a representative bar.

> Thanks for going into some more detail.

Now it would be nice if you could return the favor and answer the question:
What evidence proves the table to be a representative measure of spec compliance that hence should be published?

**Comment by RubenVerborgh** [comment]
> Focus on technical details please. You just did exactly what I asked you not to do, which makes me think you're either not listening or not willing to change your behaviour. I asked you to focus on technical details and not to make broad statements that you can not back up with any facts. And you did it twice in a row.

@michielbdejong So apparently the rules hold for everyone but yourself. If that's not lowering the bar, I don't know what is.

Then the summary is simple: no evidence has been produced that the table has any relevance or bearing in reality, and we have no reason to assume that such information exists or will be produced anytime soon. As such, the table is damaging to implementations and the ecosystem, and it is unreasonable to list implementations without their consent. This publication of known inaccurate data is a deliberate one-person action with no community support.

**Comment by kjetilk** [comment]
Let me take a middle ground here. 

First, note that no specification is at 1.0 yet. I think that is important because it hasn't been that uncommon to publish results of conformance testing without maintainer's approval, it can be thought of a service to the community and as a statement of fact, I think it is arguably a good practice, but that *has only happened after 1.0*. In the current situation, what is conformant behaviour is still somewhat in a state of flux.

Then, we also need to ensure that we have conformance tests that are thoroughly reviewed, and that we have metadata to explain what the test refers to, that it is provably legitimized by the spec, and that there is metadata to show that some tests are not yet approved. Finally, the test harness should reflect that.

Before we have all that, we can't be sufficiently confident that a test failure is the fault of the server under test and not the test or testing infrastructure, and thus it is inappropriate to publish them without the maintainer's consent. Once we have that, my opinion is that it is quite appropriate to do so.

I would like to integrate test writing into the spec review process. I have wanted to do that for years, to have text and test move together, make it part of the Definition of Done of a feature. We haven't had the resources to do that, though, I suspect it would speed up the overall ecosystem if we had that, since we'd be more confident about the impact of a certain feature if we did.

I'd rather not argue much more over this subject, but I do feel that all test suites should be held to the same standard, at least if they are to be in the solid org.

**Comment by michielbdejong** [comment]
Thanks! @csarven We're waiting for you to fill in [the doodle](https://doodle.com/meeting/organize/id/av2R180a) so we can discuss this issue in the panel.

**Comment by RubenVerborgh** [comment]
I've taken some time to reflect on this thread, and will follow in @kjetilk and @edwardsph's footsteps to provide my input to the upcoming test suite panel meeting.

**Summary: I think no test results table should be included at this point in time, given that no one currently can attest to the meaning, representativeness, correctness, and quality of its contents, and in fact to the contrary."**
I will support this statement below.

----

One the one hand, we have test-suite creator and sole maintainer @michielbdejong claiming:

> The main reason is that some implementers go through the effort of properly testing their server, but some don't. So that approach would lead to incomplete and incorrect data.

> We owe it to our readers to give a complete and honest report of the objective data

However:
- test-suite itself seems to be untested.
- test-suite itself has no quality control.
- We know the data [is](https://github.com/solid/test-suite/issues/133) [incomplete](https://github.com/solid/test-suite/issues/135) and [incorrect](https://github.com/solid/web-access-control-tests/commit/97eafaef6ada78c9e918ca89ab9383a90c14c421).

In particular, I find it highly problematic that the only quality control consists of asking implementers to spot bugs.
From a Community Solid Server perspective, our server implementation has identified—and continues to identify—far more issues in test-suite than test-suite ever has found.  Yet at the same time, the author of test-suite insists to publish information about CSS that has not undergone any quality control; information which we know in fact to be incorrect.

----

To show the severity of the lack of quality control: the current table shows tick marks in the WAC column for Node Solid Server, PHP Solid Server, Solid-Nextcloud. These tick marks have been there for several months. One would think this to be a signal of whether these implementations comply to the Solid specifications.

Unfortunately, as I just discovered, what test-suite actually checks is whether implementations have the same RDF parser bug as Node Solid Server. So in order to _pass_ test-suite, you _need_ to have an RDF parser bug.

Since [more than 2 months](https://github.com/solid/web-access-control-tests/commit/97eafaef6ada78c9e918ca89ab9383a90c14c421), **21 out of 93 tests (23% of tests) for WAC _mandate_ the server to accept invalid RDF—and servers are publicly reported to happily pass these tests**.

In other words, to tackle both the issues of representativeness and quality: **nearly a quarter of tests are dedicated to ensure that one specific bug is present in any server**. No one noticed at any given point. That is a serious cause of concern for all of us.

NSS has been passing these tests for months now; and supposedly so have PHP Solid Server Solid-Nextcloud.
Either that, or the table is outdated. One of these should be sufficient cause to say: this table is highly premature, untested, and cannot deliver the objective information it is supposed to. As such, it is harmful to the community and we should not have it out yet. We don't know what its contents mean and @michielbdejong has been unable to explain this either—all we do know for sure is that there is incorrect and misleading information in there.

----

With this in mind, my questions for the test suite panel are:
1. How is the quality of the test-suite table assessed?
2. How is the representativeness of the test-suite table assessed?
3. To what extent are the current table entries correct and representative?
4. Failing 1/2/3, should the table be depublished?
5. What criteria should be met before the table can be published?

**Comment by michielbdejong** [comment]
Thanks for your input, all!
We'll discuss it in the panel.

**Comment by bourgeoa** [comment]
> Since [more than 2 months](https://github.com/solid/web-access-control-tests/commit/97eafaef6ada78c9e918ca89ab9383a90c14c421), at least 21 out of 93 tests (23% of tests) for WAC mandate the server to accept invalid RDF

@RubenVerborgh I'm sorry to discover that the RDF is invalid.
I need some more information on the RDF error to be able to correct it in the tests and/or on the NSS server.

**Comment by edwardsph** [comment]
I'm not sure the RDF used in the tests is actually invalid. This is because the fragments used in the tests don't actually contain any triples. The code
```
    "@prefix solid: <http://www.w3.org/ns/solid/terms#>." +
    "#patch a solid:InsertDeletePatch;" +
    "  solid:inserts { <#patch> <#to> <#create> .}.",
``` 
generates
```
@prefix solid: <http://www.w3.org/ns/solid/terms#>.#patch a solid:InsertDeletePatch;  solid:inserts { <#patch> <#to> <#create> .}.
```
So that line represents a `prefix` follows by a comment from the second `#` onwards. 

The tests all succeed at submitting an empty patch. This may confirm the access control aspects of the mechanism but only on the assumption that the server hasn't gone "Oh - you sent me nothing - ok that's fine, you can do that".

If the patch actually has an effect and inserts a triple then that would be a serious RDF parser error but I don't think that is proven as the tests don't actually confirm anything changed.

**Comment by edwardsph** [comment]
I should add that the type `solid:InsertDeletePatch` is not actually in the vocab at http://www.w3.org/ns/solid/terms#

**Comment by edwardsph** [comment]
On reading the spec more, I would expect these tests to fail as the spec [says](https://solidproject.org/ED/protocol#server-patch-n3-patches)
> A patch document MUST contain one or more patch resources.

I would therefore expect all these tests to get a 422 response from a server unless I have mis-read something.

**Comment by RubenVerborgh** [comment]
> I'm not sure the RDF used in the tests is actually invalid. This is because the fragments used in the tests don't actually contain any triples.

@edwardsph You are correct.

**Comment by RubenVerborgh** [comment]
Given that some questions raised in this thread were left unanswered (notably "What evidence proves the table to be a representative measure of spec compliance […]?"), I have created separate issues to follow up on them:

- https://github.com/solid-contrib/test-suite/issues/138
- https://github.com/solid-contrib/test-suite/issues/139
- https://github.com/solid-contrib/test-suite/issues/140

That way, we can use this issue to decide whether table entries should be published without consent. The other issues then cover to what extent rows in that table have relevant meaning.

**Comment by michielbdejong** [comment]
Thanks for digging into it @edwardsph, I created https://github.com/solid-contrib/web-access-control-tests/issues/47 about it.

**Comment by michielbdejong** [comment]
Discussion continued in https://github.com/solid/test-suite-panel/issues/5
